// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReData.Infrastructure;

#nullable disable

namespace ReData.Infrastructure.Migrations
{
    [DbContext(typeof(MainDatabaseContext))]
    [Migration("20240618231408_InitialDataSources")]
    partial class InitialDataSources
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReData.Infrastructure.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DataSources");

                    b.HasDiscriminator<int>("Type").HasValue(0);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ReData.Infrastructure.Entities.CsvDataSource", b =>
                {
                    b.HasBaseType("ReData.Infrastructure.Entities.DataSource");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("ReData.Infrastructure.Entities.PostgresDataSource", b =>
                {
                    b.HasBaseType("ReData.Infrastructure.Entities.DataSource");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("ReData.Infrastructure.Entities.CsvDataSource", b =>
                {
                    b.OwnsOne("ReData.Infrastructure.Entities.CsvDataSourceOptions", "Options", b1 =>
                        {
                            b1.Property<Guid>("CsvDataSourceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CsvDataSourceId");

                            b1.ToTable("DataSources");

                            b1.ToJson("CsvOptions");

                            b1.WithOwner()
                                .HasForeignKey("CsvDataSourceId");
                        });

                    b.Navigation("Options")
                        .IsRequired();
                });

            modelBuilder.Entity("ReData.Infrastructure.Entities.PostgresDataSource", b =>
                {
                    b.OwnsOne("ReData.Infrastructure.Entities.PostgresDataSourceOptions", "Options", b1 =>
                        {
                            b1.Property<Guid>("PostgresDataSourceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Database")
                                .HasColumnType("text");

                            b1.Property<string>("Host")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Password")
                                .HasColumnType("text");

                            b1.Property<long?>("Port")
                                .HasColumnType("bigint");

                            b1.Property<string>("Username")
                                .HasColumnType("text");

                            b1.HasKey("PostgresDataSourceId");

                            b1.ToTable("DataSources");

                            b1.ToJson("PostgresOptions");

                            b1.WithOwner()
                                .HasForeignKey("PostgresDataSourceId");
                        });

                    b.Navigation("Options")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
