/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Данные
 */
export interface CreateDataConnectorResponse { 
    /**
     * Id нового коннектора данных
     */
    id: string;
    /**
     * Имя нового коннектора данных
     */
    name: string;
}

