/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataType } from './data-type';


export interface DataSetField { 
    alias: string;
    dataType: DataType;
    canBeNull: boolean;
}



