/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExprSpan } from './expr-span';


export interface ExprError { 
    span: ExprSpan;
    /**
     * Сообщение об ошибке
     */
    message: string;
}

