/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataType } from './data-type';


/**
 * Тип аргумента функции.
 */
export interface FunctionArgumentType { 
    dataType: DataType;
    /**
     * Может ли аргумент принимать NULL.
     */
    canBeNull: boolean;
}



