/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataType } from './data-type';


/**
 * Тип возвращаемого значения функции. Определяет тип данных, возможность быть NULL и является ли результат агрегированным.
 */
export interface FunctionReturnType { 
    dataType: DataType;
    /**
     * Может ли функция возвращать NULL значение.
     */
    canBeNull: boolean;
    /**
     * Является ли функция агрегирующей (вычисляющей значение по набору данных). true - функция агрегирует данные (например, SUM, COUNT) false - функция работает с отдельными значениями
     */
    aggregated?: boolean;
}



