/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * the error details object
 */
export interface ProblemDetailsError { 
    /**
     * the name of the error or property of the dto that caused the error
     */
    name?: string;
    /**
     * the reason for the error
     */
    reason?: string;
    /**
     * the code of the error
     */
    code?: string | null;
    /**
     * the severity of the error
     */
    severity?: string | null;
}

