/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransformFieldViewModel } from './transform-field-view-model';


/**
 * Ответ после применения трансформаций
 */
export interface TransformResponse { 
    /**
     * Полученные поля после применения трансформаций
     */
    fields: Array<TransformFieldViewModel>;
    /**
     * Общее количество данных подходящих под составленный запрос
     */
    total: number | null;
    /**
     * Одна страница данных соответствующих запросу
     */
    data: Array<{ [key: string]: object | undefined; }>;
}

