/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransformationBlockResponse } from './transformation-block-response';


export interface UpdateDataSetResponse { 
    id: string;
    name: string;
    dataConnectorId: string;
    transformations: Array<TransformationBlockResponse>;
}

