/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateDataConnectorResponse } from '../model/models';
import { DataConnectorListItem } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateDataConnectorRequestParams {
    name: string;
    separator: string;
    withHeader: boolean;
    file: Blob;
}


export interface DataConnectorsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Создать коннектор данных
     * Создаёт коннектор данных из поданного CSV файла и конфигурации
     * @endpoint post /api/data-connectors
* @param requestParameters
     */
    createDataConnector(requestParameters: CreateDataConnectorRequestParams, extraHttpRequestParams?: any): Observable<CreateDataConnectorResponse>;

    /**
     * Получить все коннекторы данных
     * Возвращает список всех коннекторов данных
     * @endpoint get /api/data-connectors
*/
    getAllDataConnectors(extraHttpRequestParams?: any): Observable<Array<DataConnectorListItem>>;

}
