/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateDataConnectorResponse } from '../model/models';
import { DataConnectorListItem } from '../model/models';
import { FunctionResponse } from '../model/models';
import { ProblemDetails } from '../model/models';
import { TransformErrorResponse } from '../model/models';
import { TransformRequest } from '../model/models';
import { TransformResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateDataConnectorRequestParams {
    name: string;
    separator: string;
    withHeader: boolean;
    file: Blob;
}

export interface TransformRequestParams {
    transformRequest: TransformRequest;
}


export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Создать коннектор данных (файл)
     * 
     * @endpoint post /api/data-connectors
* @param requestParameters
     */
    createDataConnector(requestParameters: CreateDataConnectorRequestParams, extraHttpRequestParams?: any): Observable<CreateDataConnectorResponse>;

    /**
     * 
     * 
     * @endpoint get /api/data-connectors
*/
    getAllDataConnectors(extraHttpRequestParams?: any): Observable<Array<DataConnectorListItem>>;

    /**
     * Получить все функции
     * Возвращает полный список доступных для провайдера PostgreSql функций
     * @endpoint get /api/functions
*/
    getAllFunctions(extraHttpRequestParams?: any): Observable<Array<FunctionResponse>>;

    /**
     * 
     * 
     * @endpoint post /api/transform
* @param requestParameters
     */
    transform(requestParameters: TransformRequestParams, extraHttpRequestParams?: any): Observable<TransformResponse>;

}
