/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FunctionResponse } from '../model/models';
import { ProblemDetails } from '../model/models';
import { TransformErrorResponse } from '../model/models';
import { TransformRequest } from '../model/models';
import { TransformResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface TransformRequestParams {
    transformRequest: TransformRequest;
}


export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Получить все функции
     * Возвращает полный список доступных для провайдера PostgreSql функций
     * @endpoint get /api/functions
*/
    getAllFunctions(extraHttpRequestParams?: any): Observable<Array<FunctionResponse>>;

    /**
     * Трансформации
     * Выполняет трансформации от заданного коннектора И выдает постранично полученные данные
     * @endpoint post /api/transform
* @param requestParameters
     */
    transform(requestParameters: TransformRequestParams, extraHttpRequestParams?: any): Observable<TransformResponse>;

}
