// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReData.DemoApplication.Database;

#nullable disable

namespace ReData.DemoApplication.Database.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    partial class ApplicationDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReData.DemoApplication.Database.Entities.DataSetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DataSets", (string)null);
                });

            modelBuilder.Entity("ReData.DemoApplication.Database.Entities.TransformationEntity", b =>
                {
                    b.Property<Guid>("DataSetId")
                        .HasColumnType("uuid");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("DataSetEntityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.HasKey("DataSetId", "Order");

                    b.HasIndex("DataSetEntityId");

                    b.ToTable("Transformations", (string)null);
                });

            modelBuilder.Entity("ReData.DemoApplication.Database.Entities.TransformationEntity", b =>
                {
                    b.HasOne("ReData.DemoApplication.Database.Entities.DataSetEntity", null)
                        .WithMany("Transformations")
                        .HasForeignKey("DataSetEntityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ReData.DemoApplication.Database.Entities.DataSetEntity", b =>
                {
                    b.Navigation("Transformations");
                });
#pragma warning restore 612, 618
        }
    }
}
