export * from './data-connectors.service';
import { DataConnectorsService } from './data-connectors.service';
export * from './data-connectors.serviceInterface';
export * from './datasets.service';
import { DatasetsService } from './datasets.service';
export * from './datasets.serviceInterface';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './default.serviceInterface';
export const APIS = [DataConnectorsService, DatasetsService, DefaultService];
