/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Базовые типы данных в системе типов. Определяет примитивные типы, с которыми работают функции.
 */
export enum DataType {

    Unknown = 0,

    Null = 1,

    Number = 2,

    Integer = 3,

    Text = 4,

    Bool = 5,

    DateTime = 6
}

