/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSetField } from './data-set-field';


/**
 * Модель отображения набора данных в таблице
 */
export interface DataSetListItem { 
    /**
     * Id
     */
    id: string;
    /**
     * Название
     */
    name: string;
    /**
     * Дата и время создания
     */
    createdAt: string;
    /**
     * Дата и время последнего обновления
     */
    updatedAt: string;
    /**
     * Количество строк при последнем сохранении
     */
    rowsCount: number | null;
    /**
     * Конечный набор полей при последнем сохранении
     */
    fieldList: Array<DataSetField> | null;
}

