/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * the dto used to send an error response to the client
 */
export interface ErrorResponse { 
    /**
     * the http status code sent to the client. default is 400.
     */
    statusCode?: number;
    /**
     * the message for the error response
     */
    message?: string;
    /**
     * the collection of errors for the current context
     */
    errors?: { [key: string]: Array<string> | undefined; };
}

