/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FunctionArgumentType } from './function-argument-type';


/**
 * Аргумент функции. Содержит информацию о параметре, который передается в функцию.
 */
export interface FunctionArgument { 
    /**
     * Название аргумента.
     */
    name: string;
    type: FunctionArgumentType;
    /**
     * Определяет пропагирует ли аргумент null если сам будет null
     */
    propagateNull: boolean;
}

