/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Категория функции, определяющая способ её вызова и синтаксис использования.
 */
export enum FunctionKind {

    Default = 0,

    Method = 1,

    Binary = 2,

    Unary = 3
}

