/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FunctionKind } from './function-kind';
import { FunctionArgument } from './function-argument';
import { FunctionReturnType } from './function-return-type';


/**
 * Описание функции, доступной для вызова в системе. Предназначено для отображения пользователю списка всех доступных функций с их параметрами и документацией.
 */
export interface FunctionResponse { 
    /**
     * Название функции для вызова. Используется в синтаксисе вызова: Name(аргумент1, аргумент2)
     */
    name: string;
    /**
     * Документация по функции - описание что делает функция и как её использовать. Может быть null если документация отсутствует.
     */
    doc: string | null;
    /**
     * Список аргументов функции в порядке их передачи. Определяет сигнатуру вызова: Name(аргумент1, аргумент2)
     */
    arguments: Array<FunctionArgument>;
    returnType: FunctionReturnType;
    kind: FunctionKind;
    /**
     * Текстовое представление функции для отображения пользователю. Обычно содержит сигнатуру функции в читаемом формате.
     */
    displayText: string;
}



