/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Transformation } from './transformation';
import { SelectItem } from './select-item';


export interface GroupByTransformation extends Transformation { 
    groups?: Array<SelectItem>;
    items?: Array<SelectItem>;
}

