/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Transformation } from './transformation';


export interface LimitOffsetTransformation extends Transformation { 
    limit?: number | null;
    offset?: number | null;
}

