/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Transformation } from './transformation';
import { OrderItem } from './order-item';


export interface OrderByTransformation extends Transformation { 
    items?: Array<OrderItem>;
}

