/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Transformation } from './transformation';
import { SelectRestOptions } from './select-rest-options';
import { SelectItem } from './select-item';


export interface SelectTransformation extends Transformation { 
    items?: Array<SelectItem>;
    restOptions?: SelectRestOptions;
}



