/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Опция для трансформации, что делать с не указанными полями
 */
export enum SelectRestOptions {

    NoAction = 1,

    Delete = 2
}

