/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ITransformation } from './i-transformation';


export interface TransformRequest { 
    dataConnectorId: string;
    pageNumber: number;
    pageSize: number;
    orderByName?: string | null;
    orderByDescending?: boolean | null;
    transformations: Array<ITransformation>;
}

