/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ITransformation } from './i-transformation';


export interface TransformationBlockResponse { 
    enabled: boolean;
    description: string | null;
    transformation: ITransformation;
}

