/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransformFieldViewModel } from './transform-field-view-model';


export interface TransformResponse { 
    fields: Array<TransformFieldViewModel>;
    total: number | null;
    data: Array<{ [key: string]: object | undefined; }>;
}

