/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataType } from './data-type';


/**
 * Информация по полю полученных данных
 */
export interface TransformFieldViewModel { 
    /**
     * Наименование поля
     */
    alias: string;
    type: DataType;
    /**
     * Может ли поле быть `null`
     */
    canBeNull: boolean;
}



