/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExprError } from './expr-error';


export interface TransformErrorResponse { 
    /**
     * Номер включенной трансформации в которой была обнаружена ошибка
     */
    index: number;
    /**
     * Сообщение об найденной ошибке
     */
    message: string;
    /**
     * Ошибки найденные при работе с выражениями
     */
    errors: Array<Array<ExprError>> | null;
}

