/**
 * ReData.DemoApp
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransformationBlock } from './transformation-block';


export interface UpdateDataSetRequest { 
    name: string;
    connectorId: string;
    transformations: Array<TransformationBlock>;
}

