// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReData.Database;

#nullable disable

namespace ReData.Database.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    [Migration("20240808215428_DataSetFirstPass")]
    partial class DataSetFirstPass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReData.Database.Entities.DataSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DataSets", (string)null);
                });

            modelBuilder.Entity("ReData.Database.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DataSources", (string)null);
                });

            modelBuilder.Entity("ReData.Database.Entities.DataSourceParameter", b =>
                {
                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DataSourceId", "Key");

                    b.ToTable("DataSourceParameter", (string)null);
                });

            modelBuilder.Entity("ReData.Database.Entities.Transformation", b =>
                {
                    b.Property<Guid>("DataSetId")
                        .HasColumnType("uuid");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("DataSetId", "Order");

                    b.ToTable("Transformations", (string)null);
                });

            modelBuilder.Entity("ReData.Database.Entities.DataSourceParameter", b =>
                {
                    b.HasOne("ReData.Database.Entities.DataSource", null)
                        .WithMany("Parameters")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReData.Database.Entities.Transformation", b =>
                {
                    b.HasOne("ReData.Database.Entities.DataSet", null)
                        .WithMany("Transformations")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReData.Database.Entities.DataSet", b =>
                {
                    b.Navigation("Transformations");
                });

            modelBuilder.Entity("ReData.Database.Entities.DataSource", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
